#!/usr/bin/env bash
set -euo pipefail

ignore() {
  
  usage() {
    echo "Usage: $0 [-i] language"
    exit 1
  }

  if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    usage
  fi

  repo_url="https://github.com/github/gitignore"
  branch="main"
  raw_url="$repo_url/raw/$branch"

  check_cert_param=""
  lang=""
  if [ "$#" -eq 2 ]; then
    if [ "$1" == "-i" ]; then
      check_cert_param="--no-check-certificate"
      lang="$2"
    else
      echo "Invalid option: $1" 
      usage
    fi
  else
    lang="$1"
  fi

  lang=${lang^}

  wget "$check_cert_param" -O ".gitignore" "$raw_url/$lang.gitignore" \
    || echo "Download of template .gitignore file for language $lang failed"

}

