#!/usr/bin/env bash

yadm_force_add() {
  # A workaround for a bug where yadm won't add files
  # already in another git repo (probably a git issue).
  #
  # https://github.com/TheLocehiliosan/yadm/issues/361
  #
  # Run this from the base dir with the conflicting .git/ in it.
  # Example:
  #
  #     ~/.oh-my-zsh $ myscript yadm-force-add custom/plugins/install.sh

  # Must be in the root git dir.
  if [[ ! -d ".git" ]]; then
      echo
      echo "Run from the conflicted .git repo base dir."
      echo "(I'm looking for a .git/ dir.)"
      echo
      exit 1
  fi

  tmpdir=/tmp/tmp.git

  if [[ -d $tmpdir ]]; then
      echo
      echo "Yo the temp dir already exists. Did I crash?"
      echo "Please reconcile: $tmpdir"
      echo
      exit 1
  fi

  # Git is just files.
  # So just move the .git dir away for a second.
  mv .git $tmpdir

  # yadm will respect the other repo's .gitignore file
  # so be sure to move that too.
  tmpignore=/tmp/tmp.gitignore

  if [[ -e ".gitignore" ]]; then
      mv .gitignore $tmpignore
  fi

  # Should work now.
  yadm add "$1"

  # Put the .git dir back.
  mv $tmpdir .git

  # Put the .gitignore back (if it existed).
  if [[ -e $tmpignore ]]; then
      mv $tmpignore .gitignore
  fi

  # Show the yadm status, hopefully with a successfully added file.
  yadm status
}
